"""column contraints chnaged

Revision ID: 2a99e9c42039
Revises: bc96baf1f467
Create Date: 2021-08-28 09:14:18.992569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a99e9c42039'
down_revision = 'bc96baf1f467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_default_currency', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_default_currency', 'user', ['default_currency'], unique=False)
    # ### end Alembic commands ###
